language: java
sudo: false
install: true

jdk:
- oraclejdk8

notifications:
  stage: notifications
  email:
    - dacalle@ucm.es
    - zhong.9745@gmail.com
    - carlosgcereceda@hotmail.es
    - manugm_8@hotmail.com
  on_success: always
  on_failure: always

jobs:
  include:
    - stage: compile
      script: ./gradlew classes
    - stage: test
      script: ./gradlew test
    - stage: deploy
      script: ./gradlew jar

stages:
  - compile
  - test
  - jar

