language: java
sudo: false
install: true

jdk:
- oraclejdk8

notifications:
  stage: notifications
  email:
    - dacalle@ucm.es
    - zhong.9745@gmail.com
    - carlosgcereceda@hotmail.es
    - manugm_8@hotmail.com
  on_success: always
  on_failure: always

stages:
  - build
  - test

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build -x test

test:
  stage: test
  script:
    - ./gradlew test

after_script:
- echo "End CI"
